### ISSUE TITLE
Just an idea, not an issue.

### ISSUE THREAD

**Issue by martin-zs** [mytechnotalent/Hacking-RISC-V#1]
Some people dumped and started to reverse engineer the Zero Stage BootLoader ROM used in every StarFive JH7110 SoC.

https://forum.rvspace.org/t/is-the-source-code-for-the-boot-rom-for-the-visionfive-2-available/1918/1

It would be old hat to you, but it might be the seed of an idea or two for a future chapter. Not necessary a full dump of a ROM from a JH7110 SoC (That might or might not have questionable license decisions) but the ZSBL ROM for any RISC-V SoC (hopefully one that has the source code already available),

**Comment by mytechnotalent** [comment]
Great idea @martin-zs however I wanted to stick to the ESP32-C3 without additional hardware but if there is ever time for another this is a perfect idea! 

Id like to be able to have the hardware as well.

**Comment by martin-zs** [comment]
I understand completely. But ESP chips do come with a bootloader from the factory embedded in non-modifyable ROM, so at least in theory you could dump that, but - there is always a but, copyright might rear it's ugly head. At least with the JH7110 SoC there were some serious questions raised in that thread that I pointed you to where it appears like they may have used GPL code in their ZSBL but never released the source code.

EDIT: From the "ESP32-C3 TRM (Version 1.1)" - Espressif Systems page 89
Table 3-1. Internal Memory Address Mapping

`Bus Type            Boundary Address Low Address High Address Size (KB) Target`
`Data bus                             0x3FF0_0000 0x3FF1_FFFF  128       Internal ROM 1` <<<===
`Data bus                             0x3FC8_0000 0x3FCD_FFFF  384       Internal SRAM 1`
`Instruction bus                      0x4000_0000 0x4003_FFFF  256       Internal ROM 0` <<<===
`Instruction bus                      0x4004_0000 0x4005_FFFF  128       Internal ROM 1` <<<===
`Instruction bus                      0x4037_C000 0x4037_FFFF   16       Internal SRAM 0`
`Instruction bus                      0x4038_0000 0x403D_FFFF  384       Internal SRAM 1`
`Data/Instruction bus                 0x5000_0000 0x5000_1FFF    8       RTC FAST Memory`
